name = "nettest"
pages_build_output_dir = "./"
compatibility_date = "2024-01-29"

# 环境变量配置
[vars]
ENVIRONMENT = "production"

# 生产环境配置
[env.production]
name = "nettest-prod"

[env.production.vars]
ENVIRONMENT = "production"

# 预览环境配置  
[env.preview]
name = "nettest-preview"

[env.preview.vars]
ENVIRONMENT = "preview"
